### ISSUE TITLE
DbTool.Core 中的GenerateModelCode方法有段代码存在缺陷

### ISSUE THREAD

**Issue by chenqian2008** [WeihanLi/DbTool.Packages#2]
![360截图18720115415323](https://user-images.githubusercontent.com/39323100/162350052-196a2fc9-9a09-4880-8892-bf93c68a40b8.png)
需要添加判断条件如以上

**Comment by WeihanLi** [comment]
收到，感谢反馈，欢迎 PR

**Comment by WeihanLi** [comment]
感觉可能在查询的时候直接就把这样的列给排除在外更好一些

**Comment by WeihanLi** [comment]
刚发布了一个新版本可以试一下 https://github.com/WeihanLi/DbTool/releases/tag/2.0.0

**Comment by WeihanLi** [comment]
一直没有回复，先 close 了，还有问题的话可以再开
